services:
  backend-db:
    image: postgres
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
    command: -p 5433
    ports:
      - '5433:5433'
    networks:
      - backend-net
    volumes:
      - backend-db-data:/var/lib/postgresql/data

  backend:
    build: ./mushroomAPI/mushroomAPI
    ports:
      - '4001:8080'
    depends_on:
      - backend-db
    networks:
      - backend-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=backend-db;Port=5433;Database=api;Username=api;Password=password

volumes:
  backend-db-data:

networks:
  backend-net:
